```{r fastFacts1, results='asis', echo=FALSE}
cat("Total number of protocols: ", prettyNum(numExpProtUsers[2], big.mark = ","))
```

```{r fastFacts2, results='asis', echo=FALSE}
cat("Total number of experiments: ", prettyNum(numExpProtUsers[1], big.mark = ","))
```

```{r fastFacts3, results='asis', echo=FALSE}
cat("Total number of users who have uploaded experiments: ", prettyNum(numExpProtUsers[3], big.mark = ","))
```

```{r fastFacts4, results='asis', echo=FALSE}
cat("Total number of samples measured: ", prettyNum(numExpProtUsers[4], big.mark = ","))
```

```{r fastFacts5, results='asis', echo=FALSE}
cat("<p style='margin-bottom:20px;'>", "Total number of calculated results: ", prettyNum(numExpProtUsers[5], big.mark = ","), "</p>")
```

```{r analysis, echo=FALSE, results='asis', fig.show='hold', fig.width=10, fig.height=4, cache=FALSE, dpi=300}
if (is.null(analysis) | nrow(analysis) == 1 && is.null(subjects) && is.null(values)) {
  cat("Not enough statistics yet to display chart")
} else if (is.null(analysis)) {
  cat("")
} else {
  plot3 <- ggplot(analysis, aes(recorded_date, cumulativeSum)) 
  plot3 <- plot3 + geom_step(colour = "blue", size = rel(1.3))
  plot3 <- plot3 + labs(title = "Calculated Results Over Time", x = NULL, 
                        y = "Number of Results\nCalculated to Date")
  plot3 <- plot3 + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  plot3
}
```

```{r link, echo=FALSE, results='asis', cache=FALSE}
link <- paste(getSSLString(), racas::applicationSettings$client.host, ":", 
          file.path(racas::applicationSettings$client.port,
          "dataFiles", "summaryStatistics", "summaryStatistics.csv"), 
          sep = "")
```

```{r graphLink, echo=FALSE, results='asis', cache=FALSE}
graphLink <- paste(getSSLString(), racas::applicationSettings$client.host, ":", 
          file.path(racas::applicationSettings$client.port,
          "dataFiles", "summaryStatistics", "summaryStatisticsGraphs.html"), 
          sep = "")
```

```{r goToGraphs, echo=FALSE, results='asis', cache=FALSE}
cat("<p style='margin-top:30px;'>For more graphs, <a href='",
    graphLink, "'>click here</a>", "</p>", sep="")
```

```{r details, echo=FALSE, results='asis', cache=FALSE}
if (is.na(Sys.timezone())) {
  timezone <- ""
} else {
  timezone <- Sys.timezone()
}
cat("Summary statistics generated on ", date(), " ", timezone, ". Data can be downloaded at <a href='",
    link, "'>this link</a>", sep="")
```
