Database Summary Graphs
========================================================

## Users

```{r figDim, echo = FALSE}
figWidth = min(10, max(usageTotals$protocol+2.4, 5))
```

```{r history, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.show='hold', fig.width=figWidth, fig.height=4, cache=FALSE, dpi = 300}
if (is.null(history)) {
  cat("No statistics to display")
} else {
  plot <- ggplot(history, aes(recorded_by, fill = isOld)) + 
    geom_bar(width = 0.95*usageTotals$protocol/(usageTotals$protocol+3))
  plot <- plot + guides(fill = guide_legend(title = NULL))
  plot <- plot + scale_fill_manual(drop = FALSE, values = c("blue", "#56B4E9"), 
                                     labels = c(paste("Newer than \n", 
                                     numWeeks, "Weeks", sep = " "),
                                     paste("Older than \n", numWeeks, "Weeks", sep = " ")))
  plot <- plot + labs(title = "Experiment Age", 
                        x = NULL, y = "Number of Expermients")
  plot <- plot + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  if (usageTotals$protocol > 29) {
    plot <- plot + scale_x_discrete(labels = NULL)
  } else {
    plot <- plot + theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust = 1))
  }
  plot
}
```


```{r progress, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.show='hold', fig.width=figWidth, fig.height=4, cache=FALSE, dpi = 300}
if (is.null(history)) {
  # pass -- we don't want to print this chart if it's empty
  cat("")
} else {
  plot1 <- ggplot(history, aes(recorded_by, fill = finalizationStatus)) + 
    geom_bar(width = 0.95*usageTotals$protocol/(usageTotals$protocol+3))
  plot1 <- plot1 + guides(fill = guide_legend(title = NULL))
  plot1 <- plot1 + scale_fill_manual(drop = FALSE, values = c("blue", "#56B4E9"))
  plot1 <- plot1 + labs(title = "Experiment Progress", 
                        x = NULL, y = "Number of Expermients")
  plot1 <- plot1 + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  if (usageTotals$protocol > 29) {
    plot1 <- plot1 + scale_x_discrete(labels = NULL)
  } else {
    plot1 <- plot1 + theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust = 1))
  }
  plot1
}
```

## Procedures

```{r protocols, echo=FALSE, results='asis', fig.show='hold', fig.width=10, fig.height=4, cache=FALSE, dpi = 300}
weeklyStatisticsDat <- copy(weeklyStatisticsData)
noise <- capture.output(weeklyStatisticsDat[ , cumsum := cumsum(protocol)])
sumZero <- which(weeklyStatisticsDat$cumsum == 0)
if(length(sumZero) > 0) {
  maxZeroCumSumRow <- max(sumZero)
  weeklyStatisticsDat <- weeklyStatisticsDat[maxZeroCumSumRow:nrow(weeklyStatisticsDat)]
}
if (is.null(weeklyStatisticsDat) | nrow(weeklyStatisticsDat) == 1) {
  cat("No statistics to display")
} else if (is.null(weeklyStatisticsDat)) {
  cat("")
} else {
  plot3 <- ggplot(weeklyStatisticsDat, aes(date, cumsum)) 
  plot3 <- plot3 + geom_step(colour = "blue", size = rel(1.3))
  plot3 <- plot3 + labs(title = "Protocol Creation", x = NULL, 
                        y = "Number of Protocols\nRecorded to Date")
  plot3 <- plot3 + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  plot3
}
```

```{r experiments, echo=FALSE, results='asis', fig.show='hold', fig.width=10, fig.height=4, cache=FALSE, dpi = 300}
weeklyStatisticsDat <- copy(weeklyStatisticsData)
noise <- capture.output(weeklyStatisticsDat[ , cumsum := cumsum(experiment)])
sumZero <- which(weeklyStatisticsDat$cumsum == 0)
if(length(sumZero) > 0) {
  maxZeroCumSumRow <- max(sumZero)
  weeklyStatisticsDat <- weeklyStatisticsDat[maxZeroCumSumRow:nrow(weeklyStatisticsDat)]
}
if (is.null(weeklyStatisticsDat) | nrow(weeklyStatisticsDat) == 1) {
  cat("No statistics to display")
} else if (is.null(weeklyStatisticsDat)) {
  cat("")
} else {
  plot3 <- ggplot(weeklyStatisticsDat, aes(date, cumsum)) 
  plot3 <- plot3 + geom_step(colour = "blue", size = rel(1.3))
  plot3 <- plot3 + labs(title = "Experiment Creation", x = NULL, 
                        y = "Number of Experiments\nRecorded to Date")
  plot3 <- plot3 + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  plot3
}
```

## Data

```{r analysis, echo=FALSE, results='asis', fig.show='hold', fig.width=10, fig.height=4, cache=FALSE, dpi = 300}
weeklyStatisticsDat <- copy(weeklyStatisticsData)
noise <- capture.output(weeklyStatisticsDat[ , cumsum := cumsum(analysis_group_value)])
sumZero <- which(weeklyStatisticsDat$cumsum == 0)
if(length(sumZero) > 0) {
  maxZeroCumSumRow <- max(sumZero)
  weeklyStatisticsDat <- weeklyStatisticsDat[maxZeroCumSumRow:nrow(weeklyStatisticsDat)]
}
if (is.null(weeklyStatisticsDat) | nrow(weeklyStatisticsDat) == 1) {
  cat("No statistics to display")
} else if (is.null(weeklyStatisticsDat)) {
  cat("")
} else {
  plot3 <- ggplot(weeklyStatisticsDat, aes(date, cumsum)) 
  plot3 <- plot3 + geom_step(colour = "blue", size = rel(1.3))
  plot3 <- plot3 + labs(title = "Calculated Results Over Time", x = NULL, 
                        y = "Number of Results\nCalculated to Date")
  plot3 <- plot3 + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  plot3
}
```

```{r values, echo=FALSE, results='asis', fig.show='hold', fig.width=10, fig.height=4, cache=FALSE, dpi = 300}
weeklyStatisticsDat <- copy(weeklyStatisticsData)
noise <- capture.output(weeklyStatisticsDat[ , cumsum := cumsum(subject_value)])
sumZero <- which(weeklyStatisticsDat$cumsum == 0)
if(length(sumZero) > 0) {
  maxZeroCumSumRow <- max(sumZero)
  weeklyStatisticsDat <- weeklyStatisticsDat[maxZeroCumSumRow:nrow(weeklyStatisticsDat)]
}
if (is.null(weeklyStatisticsDat) | nrow(weeklyStatisticsDat) == 1) {
  cat("No statistics to display")
} else if (is.null(weeklyStatisticsDat)) {
  cat("")
} else {
  plot4 <- ggplot(weeklyStatisticsDat, aes(date, cumsum)) 
  plot4 <- plot4 + geom_step(colour = "blue", size = rel(1.3))
  plot4 <- plot4 + labs(title = "Raw Data Points Acquired Over Time", x = NULL, 
                        y = "Number of Points\nAcquired to Date")
  plot4 <- plot4 + theme(axis.title = element_text(size = rel(1.3)), 
                         plot.title = element_text(size = rel(2)),
                         axis.text = element_text(size = rel(1.1)))
  plot4
}
```

```{r link, echo=FALSE, results='asis', cache=FALSE}
link <- paste(getSSLString(), racas::applicationSettings$client.host, ":", 
          file.path(racas::applicationSettings$client.port,
          "dataFiles", "summaryStatistics", "summaryStatistics.csv"), 
          sep = "")
```

```{r details, echo=FALSE, results='asis', cache=FALSE}
if (is.na(Sys.timezone())) {
  timezone <- ""
} else {
  timezone <- Sys.timezone()
}
cat("Summary statistics generated on ", date(), " ", timezone, ". Data can be downloaded at <a href='",
    link, "' target='_blank' >this link</a>", sep="")
```